[workspace]

members = [
    "day1",
    "day2",
    # Add more project names if needed
]

# [package]
# name = "aoc-2023"
# version = "0.1.0"
# edition = "2021"
#
# # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
# [dependencies]
